### ISSUE TITLE
[Epic] Option 4b PoC

### ISSUE THREAD

**Issue by askolesov** [cheqd/cheqd-node#11]
Option 4b: IndySDK + cosmos-rust + CosmosSDK base node

* [x] Create a node pool of 3 nodes for both DIDs and nodes (https://github.com/verim-id/verim-cosmos/issues/8)
* [x] Implement simple DID module on the node side (https://github.com/verim-id/verim-cosmos/issues/3)
  * [x] Use existing Cosmos Token framework to pay for a DID write
* [x] Use cosmos-rust to have LibIndy communicate with the pool using Cosmos protocol. (https://github.com/verim-id/verim-cosmos/issues/12)
  * [ ] Implement DID read/write CLI commands.
