### ISSUE TITLE
[Epic] Option 4b PoC: Node

### ISSUE THREAD

**Issue by Toktar** [cheqd/cheqd-node#3]
PoA:
- [x] Implement simple DID module
- [x] Add state proofs for requests
  - Client should take care of proofs. Node exposes this API by default. We don't have to anything on the node side.
- [x] Understand how fees work (https://github.com/verim-id/verim-cosmos/issues/16)
