### ISSUE TITLE
[Epic] Option 2 PoC

### ISSUE THREAD

**Issue by askolesov** [cheqd/cheqd-node#9]
- [ ] Simple DID module with CRUD + CLI (https://github.com/verim-id/verim-cosmos/issues/3)
- [ ] Local network of several nodes (https://github.com/verim-id/verim-cosmos/issues/8)
- [ ] Integration with Ursa
- [ ] Wrapper for Python or Java (https://github.com/verim-id/verim-cosmos/issues/10)
- [ ] Build for Android
- [ ] Research callbacks / async
- [ ] Research of supported target platforms for Go (ios, win, lin, mac)
